### ISSUE TITLE
Field Result Exercises

### ISSUE THREAD

**Issue by T5uy0** [CPNV-ES/maw11-jdn#31]
# Field Result Exercises

## Description

**As** user on looper application,
**I want to** be able to see every response from a field,
**In order to** compare the responses from the same field.

### 1. Title field

- [x] The field title appears at the top left of the page

### 2. Displays columns

- [x] A take column shows the timestamp of the response and redirects to responses linked to this timestamp.
- [x] A content column containing the contents of the response field associated with the timestamp.

### 3. Header title exercise

- [x] The header contains the title of the exercise to which the field is linked, and redirects to the results page for that exercise.

## Additional notes

- The timestamp is what links the answers in each field of a question together, because it is unique to each answer in an exercise.

**Comment by dieperid** [comment]
User story déplacée au sprint 4, elle n'a pas eu le temps d'être terminée durant le sprint 3.
