### ISSUE TITLE
Edit Field page 

### ISSUE THREAD

**Issue by NathanChauveau** [CPNV-ES/maw11-jdn#32]
# Edit Field page

## Description

**As** a user,
**I want to** modify an already existing field from an exercise
**In order to** update the field with the correct name and type

### 1. Dynamic exercise name

_*Given :*_ The user is on create exercise page and has create an field
_*When :*_ The user click on the 'edit' icon
_*Then :*_ 

- [x] The user is sent to Edit Field page.
- [x] The link should contain the ID of the field.
- [x] The label in the header has the name of the exercise.
- [x] Both current label and type of the field should appear in their respective text box

### 2. Update field

_*Given :*_ The user is on the Edit Field page
_*When :*_ The user has modify and click on the 'update field' button
_*Then :*_ 

- [x] The field should be updated in the database with both new name and type
- [x] The user is sent back to Create Field with the updated field in the list

**Comment by dieperid** [comment]
User story déplacée au sprint 2. L'équipe n'a pas eu le temps de travailler dessus durant le sprint 1.
