### ISSUE TITLE
Fulfill Exercises

### ISSUE THREAD

**Issue by NathanChauveau** [CPNV-ES/maw11-jdn#33]
# Fulfill exercises page

## Description
**As** a user,
**I want to** access to the fulfill page,
**In order to** answer the questions of an exercise.

### 1. Dynamic questions

_*Given :*_ The user is on Take Exercise page
_*When :*_ The user click on the 'Take It' and he is sent to the Fulfill page
_*Then :*_

- [x]  The number of question on the page should match the number of field link to the exercise in the database
- [x]  Each question of the page should have the correct name and type 

### 2. Saving

_*Given :*_ The user is on Fulfill page
_*When :*_ The user has finish to answer and click on 'save'
_*Then :*_

- [x]  The answer for each field should be saved on the database 
- [x]  After the reload of the page, each question of the exercise should contain the submitted answer of the user

### 3.Linked exercise

_*Given :*_ The user is on Fulfill page
_*When :*_ The user has finish to answer and click on 'save'
_*Then :*_

- [x] The link of the page when editing the take should be able to always send the user back to the corresponding answered exercise

**Comment by dieperid** [comment]
User story déplacée au sprint 4, elle n'a pas eu le temps d'être terminée durant le sprint 3.
