### ISSUE TITLE
Result Exercises backend

### ISSUE THREAD

**Issue by T5uy0** [CPNV-ES/maw11-jdn#34]
# Result Exercises backend

## Description

**As** developper,
**I want to** check whether the field has been filled in correctly depending on the type of field (one-line or multi-line),
**In order to** know for each response provided by the user (differentiated by the timestamp) if it has been completed, yes or no, according to its type.

### 1. Single line text
- [x] Show a green check if the answer is link to field.
- [x] Show red cross if no answer is link to field.

### 2. List of single lines
- [x] Show a green check if the answer is one line.
- [x] Show a double green check if the answer is multi-line.
- [x] Show red cross if no answer is link to field.

### 3. Multi-line text
- [x] Show a green check if the answer is one line.
- [x] Show a double green check if the answer is multi-line.
- [x] Show red cross if no answer is link to field.
   
## Additional notes

- This function contains the backend for displaying the results, with each response filtered by timestamp.

**Comment by dieperid** [comment]
User story déplacée au sprint 4, elle n'a pas eu le temps d'être terminée durant le sprint 3.
